[package]
name = "dandant"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.13.2"
bevy_rapier2d = { version = "0.25.0", features = [ "simd-stable", "debug-render-2d" ] }